# 开发环境配置
server:
  port: 7777

spring:
  # elasticsearch:
  #   rest:
  #     uris: http://localhost:9200
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.50.254:3308/ruoyi_olive?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 5  # 最小空闲连接数，保持一定数量的空闲连接，避免频繁创建和销毁连接
      maximum-pool-size: 20  # 最大连接池大小，根据系统负载调整
      connection-timeout: 300000  # 获取连接的超时时间（5分钟），可适当调整
      idle-timeout: 300000  # 空闲超时时间（5分钟），与 maxLifetime 配合使用，避免连接长期空闲
      max-lifetime: 300000  # 连接的最大生命周期（5分钟），建议设置得更短
      validation-timeout: 5000  # 连接验证的超时时间，避免长时间无法验证
  data:
    redis:
      host: 172.31.50.254
      # 密码
      password:
      port: 6379
      database: 0
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 8
          # 连接池中的最大空闲连接
          max-idle: 0
          # 连接池的最大数据库连接数
          max-active: 10
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 5s
      timeout: 5000

# jimmer
jimmer:
  show-sql: true
  pretty-sql: true
  is-foreign-key-enabled-by-default: false
  client:
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: Olive
          description: |
            111
          version: 1.0.0

storage:
  type: minio
  local:
    base-path: data/file
  minio:
    url: http://localhost:9000
    access-key: admin
    secret-key: 123456
    default-bucket: file

