# 开发环境配置
server:
  port: 7777
  # servlet:
    # 应用的访问路径统一前缀
    # context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.50.254:3308/ruoyi_olive?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 172.31.50.254
      # 密码
      password:
      port: 6379
      database: 0
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

# jimmer
jimmer:
  show-sql: true
  pretty-sql: true
  is-foreign-key-enabled-by-default: false
  
  client:
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: Olive
          description: |
            111
          version: 1.0.0

minio:
  enable: false
  downLoadLimit: 1024
  primary: MASTER
  client:
    MASTER:
      url: http://192.168.3.13:9000
      accessKey:
      secretKey:
      buketName: plaform
    SLAVE:
      url: http://192.168.3.13:9000
      accessKey:
      secretKey:
      buketName: plaform

