INSERT INTO ruoyi_olive.sys_config (config_name,config_key,config_value,config_type,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                            ('主框架页-默认皮肤样式名称','sys.index.skinName','skin-blue','Y','admin','2022-12-11 16:51:52','',NULL,'蓝色 skin-blue、绿色 skin-green、紫色 skin-purple、红色 skin-red、黄色 skin-yellow'),
                                                                                                                                            ('用户管理-账号初始密码','sys.user.initPassword','123456','Y','admin','2022-12-11 16:51:52','',NULL,'初始化密码 123456'),
                                                                                                                                            ('主框架页-侧边栏主题','sys.index.sideTheme','theme-dark','Y','admin','2022-12-11 16:51:52','',NULL,'深色主题theme-dark，浅色主题theme-light'),
                                                                                                                                            ('账号自助-验证码开关','sys.account.captchaEnabled','false','Y','admin','2022-12-11 16:51:52','admin','2023-03-20 20:40:31','是否开启验证码功能（true开启，false关闭）'),
                                                                                                                                            ('账号自助-是否开启用户注册功能','sys.account.registerUser','false','Y','admin','2022-12-11 16:51:52','',NULL,'是否开启注册用户功能（true开启，false关闭）'),
                                                                                                                                            ('测试','sys.test','test','Y','admin','2024-12-22 04:37:15','admin','2024-12-22 04:41:51','时间问题');
INSERT INTO ruoyi_olive.sys_dept (parent_id,ancestors,dept_name,order_num,leader,phone,email,status,del_flag,create_by,create_time,update_by,update_time) VALUES
                                                                                                                                                              (0,'0','若依科技',0,'若依','15888888888','ry@qq.com','0','0','admin','2022-12-11 16:51:52','',NULL),
                                                                                                                                                              (100,'0,100','深圳总公司',1,'若依','15888888888','ry@qq.com','0','0','admin','2022-12-11 16:51:52','',NULL),
                                                                                                                                                              (100,'0,100','长沙分公司',2,'若依','15888888888','ry@qq.com','0','0','admin','2022-12-11 16:51:52','',NULL),
                                                                                                                                                              (101,'0,100,101','研发部门',1,'若依','15888888888','ry@qq.com','0','0','admin','2022-12-11 16:51:52','',NULL),
                                                                                                                                                              (101,'0,100,101','市场部门',2,'若依','15888888888','ry@qq.com','0','0','admin','2022-12-11 16:51:52','',NULL),
                                                                                                                                                              (101,'0,100,101','测试部门',3,'若依','15888888888','ry@qq.com','0','0','admin','2022-12-11 16:51:52','',NULL),
                                                                                                                                                              (101,'0,100,101','财务部门',4,'若依','15888888888','ry@qq.com','0','0','admin','2022-12-11 16:51:52','',NULL),
                                                                                                                                                              (101,'0,100,101','运维部门',5,'若依','15888888888','ry@qq.com','0','0','admin','2022-12-11 16:51:52','',NULL),
                                                                                                                                                              (102,'0,100,102','市场部门',1,'若依','15888888888','ry@qq.com','0','0','admin','2022-12-11 16:51:52','',NULL),
                                                                                                                                                              (102,'0,100,102','财务部门',2,'若依','15888888888','ry@qq.com','0','0','admin','2022-12-11 16:51:52','',NULL);
INSERT INTO ruoyi_olive.sys_dict_data (dict_sort,dict_label,dict_value,dict_type,css_class,list_class,is_default,status,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                (1,'男','0','sys_user_sex','','','Y','0','admin','2022-12-11 16:51:52','',NULL,'性别男'),
                                                                                                                                                                                (2,'女','1','sys_user_sex','','','N','0','admin','2022-12-11 16:51:52','',NULL,'性别女'),
                                                                                                                                                                                (3,'未知','2','sys_user_sex','','','N','0','admin','2022-12-11 16:51:52','',NULL,'性别未知'),
                                                                                                                                                                                (1,'显示','0','sys_show_hide','','primary','Y','0','admin','2022-12-11 16:51:52','',NULL,'显示菜单'),
                                                                                                                                                                                (2,'隐藏','1','sys_show_hide','','danger','N','0','admin','2022-12-11 16:51:52','',NULL,'隐藏菜单'),
                                                                                                                                                                                (1,'正常','0','sys_normal_disable','','primary','Y','0','admin','2022-12-11 16:51:52','',NULL,'正常状态'),
                                                                                                                                                                                (2,'停用','1','sys_normal_disable','','danger','N','0','admin','2022-12-11 16:51:52','',NULL,'停用状态'),
                                                                                                                                                                                (1,'正常','0','sys_job_status','','primary','Y','0','admin','2022-12-11 16:51:52','',NULL,'正常状态'),
                                                                                                                                                                                (2,'暂停','1','sys_job_status','','danger','N','0','admin','2022-12-11 16:51:52','',NULL,'停用状态'),
                                                                                                                                                                                (1,'默认','DEFAULT','sys_job_group','','','Y','0','admin','2022-12-11 16:51:52','',NULL,'默认分组');
INSERT INTO ruoyi_olive.sys_dict_data (dict_sort,dict_label,dict_value,dict_type,css_class,list_class,is_default,status,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                (2,'系统','SYSTEM','sys_job_group','','','N','0','admin','2022-12-11 16:51:52','',NULL,'系统分组'),
                                                                                                                                                                                (1,'是','Y','sys_yes_no','','primary','Y','0','admin','2022-12-11 16:51:52','',NULL,'系统默认是'),
                                                                                                                                                                                (2,'否','N','sys_yes_no','','danger','N','0','admin','2022-12-11 16:51:52','',NULL,'系统默认否'),
                                                                                                                                                                                (1,'通知','1','sys_notice_type','','warning','Y','0','admin','2022-12-11 16:51:52','',NULL,'通知'),
                                                                                                                                                                                (2,'公告','2','sys_notice_type','','success','N','0','admin','2022-12-11 16:51:52','',NULL,'公告'),
                                                                                                                                                                                (1,'正常','0','sys_notice_status','','primary','Y','0','admin','2022-12-11 16:51:52','',NULL,'正常状态'),
                                                                                                                                                                                (2,'关闭','1','sys_notice_status','','danger','N','0','admin','2022-12-11 16:51:52','',NULL,'关闭状态'),
                                                                                                                                                                                (99,'其他','0','sys_oper_type','','info','N','0','admin','2022-12-11 16:51:52','',NULL,'其他操作'),
                                                                                                                                                                                (1,'新增','1','sys_oper_type','','info','N','0','admin','2022-12-11 16:51:52','',NULL,'新增操作'),
                                                                                                                                                                                (2,'修改','2','sys_oper_type','','info','N','0','admin','2022-12-11 16:51:52','',NULL,'修改操作');
INSERT INTO ruoyi_olive.sys_dict_data (dict_sort,dict_label,dict_value,dict_type,css_class,list_class,is_default,status,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                (3,'删除','3','sys_oper_type','','danger','N','0','admin','2022-12-11 16:51:52','',NULL,'删除操作'),
                                                                                                                                                                                (4,'授权','4','sys_oper_type','','primary','N','0','admin','2022-12-11 16:51:52','',NULL,'授权操作'),
                                                                                                                                                                                (5,'导出','5','sys_oper_type','','warning','N','0','admin','2022-12-11 16:51:52','',NULL,'导出操作'),
                                                                                                                                                                                (6,'导入','6','sys_oper_type','','warning','N','0','admin','2022-12-11 16:51:52','',NULL,'导入操作'),
                                                                                                                                                                                (7,'强退','7','sys_oper_type','','danger','N','0','admin','2022-12-11 16:51:52','',NULL,'强退操作'),
                                                                                                                                                                                (8,'生成代码','8','sys_oper_type','','warning','N','0','admin','2022-12-11 16:51:52','',NULL,'生成操作'),
                                                                                                                                                                                (9,'清空数据','9','sys_oper_type','','danger','N','0','admin','2022-12-11 16:51:52','',NULL,'清空操作'),
                                                                                                                                                                                (1,'成功','0','sys_common_status','','primary','N','0','admin','2022-12-11 16:51:52','',NULL,'正常状态'),
                                                                                                                                                                                (2,'失败','1','sys_common_status','','danger','N','0','admin','2022-12-11 16:51:52','',NULL,'停用状态'),
                                                                                                                                                                                (0,'请假流程','leave','sys_process_category',NULL,'default','N','0','admin','2022-12-12 11:17:56','',NULL,NULL);
INSERT INTO ruoyi_olive.sys_dict_data (dict_sort,dict_label,dict_value,dict_type,css_class,list_class,is_default,status,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                (0,'OA流程','oa','sys_process_category',NULL,'default','N','0','admin','2022-12-12 11:18:08','',NULL,NULL),
                                                                                                                                                                                (0,'正常','0','common_status',NULL,'primary','N','0','admin','2022-12-18 22:01:08','admin','2023-03-14 21:14:11',NULL),
                                                                                                                                                                                (1,'禁用','1','common_status',NULL,'danger','N','0','admin','2022-12-18 22:01:21','',NULL,NULL),
                                                                                                                                                                                (0,'任务监听','1','sys_listener_type',NULL,'default','N','0','admin','2022-12-25 11:47:26','',NULL,NULL),
                                                                                                                                                                                (2,'执行监听','2','sys_listener_type',NULL,'default','N','0','admin','2022-12-25 11:47:37','',NULL,NULL),
                                                                                                                                                                                (0,'JAVA类','classListener','sys_listener_value_type',NULL,'default','N','0','admin','2022-12-25 11:48:55','admin','2023-02-18 19:16:46',NULL),
                                                                                                                                                                                (0,'表达式','expressionListener','sys_listener_value_type',NULL,'default','N','0','admin','2022-12-25 11:49:05','admin','2023-02-18 19:16:56',NULL),
                                                                                                                                                                                (0,'代理表达式','delegateExpressionListener','sys_listener_value_type',NULL,'default','N','0','admin','2022-12-25 11:49:16','admin','2023-02-18 19:17:04',NULL),
                                                                                                                                                                                (0,'系统指定','fixed','exp_data_type',NULL,'primary','N','0','admin','2023-03-04 17:34:16','admin','2023-11-09 22:18:06',NULL),
                                                                                                                                                                                (0,'动态选择','dynamic','exp_data_type',NULL,'danger','N','0','admin','2023-03-04 17:34:26','admin','2023-11-09 22:18:16',NULL);
INSERT INTO ruoyi_olive.sys_dict_data (dict_sort,dict_label,dict_value,dict_type,css_class,list_class,is_default,status,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                (0,'未读','0','copy_message_status',NULL,'info','N','0','admin','2023-03-18 14:30:00','',NULL,NULL),
                                                                                                                                                                                (1,'已读','1','copy_message_status',NULL,'primary','N','0','admin','2023-03-18 14:30:20','admin','2023-03-18 14:30:26',NULL),
                                                                                                                                                                                (0,'路由表单','route','form_type',NULL,'primary','N','0','admin','2023-11-07 09:08:25','admin','2023-11-14 08:29:58',NULL),
                                                                                                                                                                                (1,'在线表单','online','form_type',NULL,'success','N','0','admin','2023-11-07 09:08:40','admin','2023-11-14 08:29:52',NULL),
                                                                                                                                                                                (0,'全部','all','exp_suit_type',NULL,'primary','N','0','admin','2023-11-09 21:48:21','admin','2023-11-09 22:17:14',NULL),
                                                                                                                                                                                (0,'办理人','assignee','exp_suit_type',NULL,'primary','N','0','admin','2023-11-09 21:49:00','admin','2023-11-09 22:17:20',NULL),
                                                                                                                                                                                (0,'候选人','users','exp_suit_type',NULL,'primary','N','0','admin','2023-11-09 21:49:11','admin','2023-11-09 22:17:25',NULL),
                                                                                                                                                                                (0,'角色','role','exp_suit_type',NULL,'primary','N','0','admin','2023-11-09 21:49:23','admin','2023-11-09 22:17:29',NULL),
                                                                                                                                                                                (0,'部门','dept','exp_suit_type',NULL,'primary','N','0','admin','2023-11-09 21:49:32','admin','2023-11-09 22:17:34',NULL),
                                                                                                                                                                                (0,'岗位','post','exp_suit_type',NULL,'primary','N','0','admin','2023-11-09 21:49:42','admin','2023-11-09 22:17:39',NULL);
INSERT INTO ruoyi_olive.sys_dict_data (dict_sort,dict_label,dict_value,dict_type,css_class,list_class,is_default,status,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                (7,'会签','multi','exp_suit_type',NULL,'primary','N','0','admin','2023-12-08 09:55:40','',NULL,NULL),
                                                                                                                                                                                (0,'添加测试数据1','test_11','test_1',NULL,'default','N','0','',NULL,'',NULL,'修改测试'),
                                                                                                                                                                                (0,'添加测试_2','test_222','test_1',NULL,'default','N','0','admin','2024-12-21 23:07:07','admin','2024-12-21 23:07:07','222'),
                                                                                                                                                                                (0,'事务测试','test_3','test_1',NULL,'default','N','0','admin','2024-12-21 23:10:14','admin','2024-12-21 23:46:12','shiwu');
INSERT INTO ruoyi_olive.sys_dict_type (dict_name,dict_type,status,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                          ('用户性别','sys_user_sex','0','admin','2022-12-11 16:51:52','',NULL,'用户性别列表'),
                                                                                                                          ('菜单状态','sys_show_hide','0','admin','2022-12-11 16:51:52','',NULL,'菜单状态列表'),
                                                                                                                          ('系统开关','sys_normal_disable','0','admin','2022-12-11 16:51:52','',NULL,'系统开关列表'),
                                                                                                                          ('任务状态','sys_job_status','0','admin','2022-12-11 16:51:52','',NULL,'任务状态列表'),
                                                                                                                          ('任务分组','sys_job_group','0','admin','2022-12-11 16:51:52','',NULL,'任务分组列表'),
                                                                                                                          ('系统是否','sys_yes_no','0','admin','2022-12-11 16:51:52','',NULL,'系统是否列表'),
                                                                                                                          ('通知类型','sys_notice_type','0','admin','2022-12-11 16:51:52','',NULL,'通知类型列表'),
                                                                                                                          ('通知状态','sys_notice_status','0','admin','2022-12-11 16:51:52','',NULL,'通知状态列表'),
                                                                                                                          ('操作类型','sys_oper_type','0','admin','2022-12-11 16:51:52','',NULL,'操作类型列表'),
                                                                                                                          ('系统状态','sys_common_status','0','admin','2022-12-11 16:51:52','',NULL,'登录状态列表');
INSERT INTO ruoyi_olive.sys_dict_type (dict_name,dict_type,status,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                          ('流程分类','sys_process_category','0','admin','2022-12-12 11:17:38','',NULL,NULL),
                                                                                                                          ('通用状态','common_status','0','admin','2022-12-18 22:00:02','',NULL,NULL),
                                                                                                                          ('监听类型','sys_listener_type','0','admin','2022-12-18 22:03:07','',NULL,NULL),
                                                                                                                          ('监听值类型','sys_listener_value_type','0','admin','2022-12-18 22:03:39','',NULL,NULL),
                                                                                                                          ('监听属性','sys_listener_event_type','0','admin','2022-12-18 22:04:29','',NULL,NULL),
                                                                                                                          ('表达式指定类型','exp_data_type','0','admin','2023-03-04 17:32:50','admin','2023-11-09 21:47:59',NULL),
                                                                                                                          ('抄送任务阅读状态','copy_message_status','0','admin','2023-03-18 14:29:31','',NULL,NULL),
                                                                                                                          ('表单类型','form_type','0','admin','2023-11-07 09:07:51','',NULL,NULL),
                                                                                                                          ('表达式适用类型','exp_suit_type','0','admin','2023-11-09 21:47:49','',NULL,NULL),
                                                                                                                          ('测试1','test_1','0','',NULL,'',NULL,NULL);
INSERT INTO ruoyi_olive.sys_job (job_name,job_group,invoke_target,cron_expression,misfire_policy,concurrent,status,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                           ('系统默认（无参）','DEFAULT','ryTask.ryNoParams','0/10 * * * * ?','3','1','1','admin','2022-12-11 16:51:52','',NULL,''),
                                                                                                                                                                           ('系统默认（有参）','DEFAULT','ryTask.ryParams(''ry'')','0/15 * * * * ?','3','1','1','admin','2022-12-11 16:51:52','',NULL,''),
                                                                                                                                                                           ('系统默认（多参）','DEFAULT','ryTask.ryMultipleParams(''ry'', true, 2000L, 316.50D, 100)','0/20 * * * * ?','3','1','1','admin','2022-12-11 16:51:52','',NULL,'');
INSERT INTO ruoyi_olive.sys_login_log (user_name,ipaddr,login_location,browser,os,status,msg,login_time) VALUES
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','退出成功','2024-12-22 00:28:38'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 00:28:40'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 01:05:34'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 09:38:48'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 12:24:57'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 13:23:05'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 13:53:17'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 15:31:22'),
                                                                                                             ('tony','127.0.0.1','内网IP','Firefox 13','Windows 10','0','登录成功','2024-12-22 15:36:24'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 16:53:56');
INSERT INTO ruoyi_olive.sys_login_log (user_name,ipaddr,login_location,browser,os,status,msg,login_time) VALUES
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 17:29:19'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','退出成功','2024-12-22 18:20:28'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 18:21:35'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 19:45:52'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 21:31:35'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-22 22:25:17'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-23 10:20:31'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-23 11:20:45'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-23 13:27:52'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-31 14:58:30');
INSERT INTO ruoyi_olive.sys_login_log (user_name,ipaddr,login_location,browser,os,status,msg,login_time) VALUES
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-31 17:02:29'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-31 18:51:15'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','1','获取用户账户异常','2024-12-31 18:51:15'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-31 18:54:42'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','1','获取用户账户异常','2024-12-31 18:54:42'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-31 18:56:28'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','1','获取用户账户异常','2024-12-31 18:56:28'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-31 18:56:45'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','1','获取用户账户异常','2024-12-31 18:56:45'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-31 18:57:41');
INSERT INTO ruoyi_olive.sys_login_log (user_name,ipaddr,login_location,browser,os,status,msg,login_time) VALUES
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','1','获取用户账户异常','2024-12-31 18:59:49'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-31 19:00:08'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','1','获取用户账户异常','2024-12-31 19:07:34'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2024-12-31 19:07:48'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 17:43:32'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','1','Cannot invoke "com.olive.framework.web.system.SysUser.getPassword()" because "this.user" is null','2025-01-02 19:21:41'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','1','Cannot invoke "com.olive.framework.web.system.SysUser.getPassword()" because "this.user" is null','2025-01-02 19:26:10'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','1','Cannot invoke "com.olive.framework.web.system.SysUser.getPassword()" because "this.user" is null','2025-01-02 19:26:33'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','1','Cannot invoke "com.olive.framework.web.system.SysUser.getPassword()" because "this.user" is null','2025-01-02 19:30:54'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 19:31:14');
INSERT INTO ruoyi_olive.sys_login_log (user_name,ipaddr,login_location,browser,os,status,msg,login_time) VALUES
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 20:24:02'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 20:54:22'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 21:08:50'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 21:09:11'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 21:09:41'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 21:09:47'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 21:12:14'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 21:12:56'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 21:17:07'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-02 21:18:58');
INSERT INTO ruoyi_olive.sys_login_log (user_name,ipaddr,login_location,browser,os,status,msg,login_time) VALUES
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 11:16:08'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 11:17:35'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 11:29:27'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 11:32:15'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 11:37:29'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 11:48:18'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 11:48:37'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 11:53:20'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 16:32:17'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 17:21:20');
INSERT INTO ruoyi_olive.sys_login_log (user_name,ipaddr,login_location,browser,os,status,msg,login_time) VALUES
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 17:37:01'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','退出成功','2025-01-03 18:06:02'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 18:06:05'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','退出成功','2025-01-03 18:06:05'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 18:07:28'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','退出成功','2025-01-03 18:09:08'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 18:09:12'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 21:05:55'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-03 22:32:59'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-04 10:49:13');
INSERT INTO ruoyi_olive.sys_login_log (user_name,ipaddr,login_location,browser,os,status,msg,login_time) VALUES
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-04 13:59:47'),
                                                                                                             ('admin','127.0.0.1','内网IP','Chrome 13','Windows 10','0','登录成功','2025-01-04 15:29:14');
INSERT INTO ruoyi_olive.sys_menu (menu_name,parent_id,order_num,`path`,component,query,route_name,is_frame,is_cache,menu_type,visible,status,perms,icon,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                                                ('系统管理',0,30,'system',NULL,'','',1,0,'M','0','0','','system','admin','2024-09-13 06:08:16','admin','2024-10-31 13:24:12','系统管理目录'),
                                                                                                                                                                                                                ('系统监控',0,20,'monitor',NULL,'','',1,0,'M','0','0','','monitor','admin','2024-09-13 06:08:16','admin','2024-10-31 13:23:14','系统监控目录'),
                                                                                                                                                                                                                ('系统工具',0,21,'tool',NULL,'','',1,0,'M','0','0','','tool','admin','2024-09-13 06:08:16','admin','2024-10-31 13:23:34','系统工具目录'),
                                                                                                                                                                                                                ('用户管理',1,1,'user','system/user/index','','',1,0,'C','0','0','system:user:list','user','admin','2024-09-13 06:08:16','',NULL,'用户管理菜单'),
                                                                                                                                                                                                                ('角色管理',1,2,'role','system/role/index','','',1,0,'C','0','0','system:role:list','peoples','admin','2024-09-13 06:08:16','',NULL,'角色管理菜单'),
                                                                                                                                                                                                                ('菜单管理',1,3,'menu','system/menu/index','','',1,0,'C','0','0','system:menu:list','tree-table','admin','2024-09-13 06:08:16','',NULL,'菜单管理菜单'),
                                                                                                                                                                                                                ('部门管理',1,4,'dept','system/dept/index','','',1,0,'C','0','0','system:dept:list','tree','admin','2024-09-13 06:08:16','',NULL,'部门管理菜单'),
                                                                                                                                                                                                                ('岗位管理',1,5,'post','system/post/index','','',1,0,'C','0','0','system:post:list','post','admin','2024-09-13 06:08:16','',NULL,'岗位管理菜单'),
                                                                                                                                                                                                                ('字典管理',1,6,'dict','system/dict/index','','',1,0,'C','0','0','system:dict:list','dict','admin','2024-09-13 06:08:16','',NULL,'字典管理菜单'),
                                                                                                                                                                                                                ('参数设置',1,7,'config','system/config/index','','',1,0,'C','0','0','system:config:list','edit','admin','2024-09-13 06:08:16','',NULL,'参数设置菜单');
INSERT INTO ruoyi_olive.sys_menu (menu_name,parent_id,order_num,`path`,component,query,route_name,is_frame,is_cache,menu_type,visible,status,perms,icon,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                                                ('通知公告',1,8,'notice','system/notice/index','','',1,0,'C','0','0','system:notice:list','message','admin','2024-09-13 06:08:16','',NULL,'通知公告菜单'),
                                                                                                                                                                                                                ('日志管理',1,9,'log','','','',1,0,'M','0','0','','log','admin','2024-09-13 06:08:16','',NULL,'日志管理菜单'),
                                                                                                                                                                                                                ('在线用户',2,1,'online','monitor/online/index','','',1,0,'C','0','0','monitor:online:list','online','admin','2024-09-13 06:08:16','',NULL,'在线用户菜单'),
                                                                                                                                                                                                                ('定时任务',2,2,'job','monitor/job/index','','',1,0,'C','0','0','monitor:job:list','job','admin','2024-09-13 06:08:16','',NULL,'定时任务菜单'),
                                                                                                                                                                                                                ('数据监控',2,3,'druid','monitor/druid/index','','',1,0,'C','0','0','monitor:druid:list','druid','admin','2024-09-13 06:08:16','',NULL,'数据监控菜单'),
                                                                                                                                                                                                                ('服务监控',2,4,'server','monitor/server/index','','',1,0,'C','0','0','monitor:server:list','server','admin','2024-09-13 06:08:16','',NULL,'服务监控菜单'),
                                                                                                                                                                                                                ('缓存监控',2,5,'cache','monitor/cache/index','','',1,0,'C','0','0','monitor:cache:list','redis','admin','2024-09-13 06:08:16','',NULL,'缓存监控菜单'),
                                                                                                                                                                                                                ('缓存列表',2,6,'cacheList','monitor/cache/list','','',1,0,'C','0','0','monitor:cache:list','redis-list','admin','2024-09-13 06:08:16','',NULL,'缓存列表菜单'),
                                                                                                                                                                                                                ('表单构建',3,1,'build','tool/build/index','','',1,0,'C','0','0','tool:build:list','build','admin','2024-09-13 06:08:16','',NULL,'表单构建菜单'),
                                                                                                                                                                                                                ('代码生成',3,2,'gen','tool/gen/index','','',1,0,'C','0','0','tool:gen:list','code','admin','2024-09-13 06:09:58','',NULL,'代码生成菜单');
INSERT INTO ruoyi_olive.sys_menu (menu_name,parent_id,order_num,`path`,component,query,route_name,is_frame,is_cache,menu_type,visible,status,perms,icon,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                                                ('系统接口',3,3,'swagger','tool/swagger/index','','',1,0,'C','0','0','tool:swagger:list','swagger','admin','2024-09-13 06:08:16','',NULL,'系统接口菜单'),
                                                                                                                                                                                                                ('操作日志',108,1,'operlog','monitor/operlog/index','','',1,0,'C','0','0','monitor:operlog:list','form','admin','2024-09-13 06:08:16','',NULL,'操作日志菜单'),
                                                                                                                                                                                                                ('登录日志',108,2,'logininfor','monitor/logininfor/index','','',1,0,'C','0','0','monitor:logininfor:list','logininfor','admin','2024-09-13 06:08:16','',NULL,'登录日志菜单'),
                                                                                                                                                                                                                ('修改密码',100,8,'',NULL,NULL,NULL,1,0,'F','0','0','system:user:updatePwd','#','admin','2022-04-29 11:27:13','',NULL,''),
                                                                                                                                                                                                                ('用户查询',100,1,'','','','',1,0,'F','0','0','system:user:query','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('用户新增',100,2,'','','','',1,0,'F','0','0','system:user:add','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('用户修改',100,3,'','','','',1,0,'F','0','0','system:user:edit','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('用户删除',100,4,'','','','',1,0,'F','0','0','system:user:remove','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('用户导出',100,5,'','','','',1,0,'F','0','0','system:user:export','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('用户导入',100,6,'','','','',1,0,'F','0','0','system:user:import','#','admin','2024-09-13 06:08:16','',NULL,'');
INSERT INTO ruoyi_olive.sys_menu (menu_name,parent_id,order_num,`path`,component,query,route_name,is_frame,is_cache,menu_type,visible,status,perms,icon,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                                                ('重置密码',100,7,'','','','',1,0,'F','0','0','system:user:resetPwd','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('角色查询',101,1,'','','','',1,0,'F','0','0','system:role:query','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('角色新增',101,2,'','','','',1,0,'F','0','0','system:role:add','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('角色修改',101,3,'','','','',1,0,'F','0','0','system:role:edit','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('角色删除',101,4,'','','','',1,0,'F','0','0','system:role:remove','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('角色导出',101,5,'','','','',1,0,'F','0','0','system:role:export','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('菜单查询',102,1,'','','','',1,0,'F','0','0','system:menu:query','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('菜单新增',102,2,'','','','',1,0,'F','0','0','system:menu:add','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('菜单修改',102,3,'','','','',1,0,'F','0','0','system:menu:edit','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('菜单删除',102,4,'','','','',1,0,'F','0','0','system:menu:remove','#','admin','2024-09-13 06:08:16','',NULL,'');
INSERT INTO ruoyi_olive.sys_menu (menu_name,parent_id,order_num,`path`,component,query,route_name,is_frame,is_cache,menu_type,visible,status,perms,icon,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                                                ('部门查询',103,1,'','','','',1,0,'F','0','0','system:dept:query','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('部门新增',103,2,'','','','',1,0,'F','0','0','system:dept:add','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('部门修改',103,3,'','','','',1,0,'F','0','0','system:dept:edit','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('部门删除',103,4,'','','','',1,0,'F','0','0','system:dept:remove','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('岗位查询',104,1,'','','','',1,0,'F','0','0','system:post:query','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('岗位新增',104,2,'','','','',1,0,'F','0','0','system:post:add','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('岗位修改',104,3,'','','','',1,0,'F','0','0','system:post:edit','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('岗位删除',104,4,'','','','',1,0,'F','0','0','system:post:remove','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('岗位导出',104,5,'','','','',1,0,'F','0','0','system:post:export','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('字典查询',105,1,'#','','','',1,0,'F','0','0','system:dict:query','#','admin','2024-09-13 06:08:16','',NULL,'');
INSERT INTO ruoyi_olive.sys_menu (menu_name,parent_id,order_num,`path`,component,query,route_name,is_frame,is_cache,menu_type,visible,status,perms,icon,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                                                ('字典新增',105,2,'#','','','',1,0,'F','0','0','system:dict:add','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('字典修改',105,3,'#','','','',1,0,'F','0','0','system:dict:edit','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('字典删除',105,4,'#','','','',1,0,'F','0','0','system:dict:remove','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('字典导出',105,5,'#','','','',1,0,'F','0','0','system:dict:export','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('参数查询',106,1,'#','','','',1,0,'F','0','0','system:config:query','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('参数新增',106,2,'#','','','',1,0,'F','0','0','system:config:add','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('参数修改',106,3,'#','','','',1,0,'F','0','0','system:config:edit','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('参数删除',106,4,'#','','','',1,0,'F','0','0','system:config:remove','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('参数导出',106,5,'#','','','',1,0,'F','0','0','system:config:export','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('公告查询',107,1,'#','','','',1,0,'F','0','0','system:notice:query','#','admin','2024-09-13 06:08:16','',NULL,'');
INSERT INTO ruoyi_olive.sys_menu (menu_name,parent_id,order_num,`path`,component,query,route_name,is_frame,is_cache,menu_type,visible,status,perms,icon,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                                                ('公告新增',107,2,'#','','','',1,0,'F','0','0','system:notice:add','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('公告修改',107,3,'#','','','',1,0,'F','0','0','system:notice:edit','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('公告删除',107,4,'#','','','',1,0,'F','0','0','system:notice:remove','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('操作查询',500,1,'#','','','',1,0,'F','0','0','monitor:operlog:query','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('操作删除',500,2,'#','','','',1,0,'F','0','0','monitor:operlog:remove','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('日志导出',500,3,'#','','','',1,0,'F','0','0','monitor:operlog:export','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('登录查询',501,1,'#','','','',1,0,'F','0','0','monitor:logininfor:query','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('登录删除',501,2,'#','','','',1,0,'F','0','0','monitor:logininfor:remove','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('日志导出',501,3,'#','','','',1,0,'F','0','0','monitor:logininfor:export','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('账户解锁',501,4,'#','','','',1,0,'F','0','0','monitor:logininfor:unlock','#','admin','2024-09-13 06:08:16','',NULL,'');
INSERT INTO ruoyi_olive.sys_menu (menu_name,parent_id,order_num,`path`,component,query,route_name,is_frame,is_cache,menu_type,visible,status,perms,icon,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                                                ('在线查询',109,1,'#','','','',1,0,'F','0','0','monitor:online:query','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('批量强退',109,2,'#','','','',1,0,'F','0','0','monitor:online:batchLogout','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('单条强退',109,3,'#','','','',1,0,'F','0','0','monitor:online:forceLogout','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('任务查询',110,1,'#','','','',1,0,'F','0','0','monitor:job:query','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('任务新增',110,2,'#','','','',1,0,'F','0','0','monitor:job:add','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('任务修改',110,3,'#','','','',1,0,'F','0','0','monitor:job:edit','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('任务删除',110,4,'#','','','',1,0,'F','0','0','monitor:job:remove','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('状态修改',110,5,'#','','','',1,0,'F','0','0','monitor:job:changeStatus','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('任务导出',110,6,'#','','','',1,0,'F','0','0','monitor:job:export','#','admin','2024-09-13 06:08:16','',NULL,''),
                                                                                                                                                                                                                ('生成查询',116,1,'#','','','',1,0,'F','0','0','tool:gen:query','#','admin','2024-09-13 06:09:58','',NULL,'');
INSERT INTO ruoyi_olive.sys_menu (menu_name,parent_id,order_num,`path`,component,query,route_name,is_frame,is_cache,menu_type,visible,status,perms,icon,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                                                ('生成修改',116,2,'#','','','',1,0,'F','0','0','tool:gen:edit','#','admin','2024-09-13 06:09:58','',NULL,''),
                                                                                                                                                                                                                ('生成删除',116,3,'#','','','',1,0,'F','0','0','tool:gen:remove','#','admin','2024-09-13 06:09:58','',NULL,''),
                                                                                                                                                                                                                ('导入代码',116,4,'#','','','',1,0,'F','0','0','tool:gen:import','#','admin','2024-09-13 06:09:58','',NULL,''),
                                                                                                                                                                                                                ('预览代码',116,5,'#','','','',1,0,'F','0','0','tool:gen:preview','#','admin','2024-09-13 06:09:58','',NULL,''),
                                                                                                                                                                                                                ('生成代码',116,6,'#','','','',1,0,'F','0','0','tool:gen:code','#','admin','2024-09-13 06:09:58','',NULL,''),
                                                                                                                                                                                                                ('测试2',0,100,'/test/111',NULL,NULL,NULL,1,0,'M','0','0',NULL,'bug','admin','2024-12-22 14:42:04','admin','2024-12-22 14:42:04',''),
                                                                                                                                                                                                                ('子目录测试1',1151,2,'qqq',NULL,NULL,NULL,1,0,'M','0','0',NULL,'404','admin','2024-12-22 14:42:53','admin','2024-12-22 14:45:47',''),
                                                                                                                                                                                                                ('子目录测试12',1151,0,'11',NULL,NULL,NULL,1,0,'M','0','0',NULL,'bug','admin','2024-12-22 14:48:37','admin','2024-12-22 14:48:37','');
INSERT INTO ruoyi_olive.sys_notice (notice_title,notice_type,notice_content,status,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                           ('温馨提醒：2018-07-01 若依新版本发布啦','2',0xE696B0E78988E69CACE58685E5AEB9,'0','admin','2022-12-11 16:51:52','',NULL,'管理员'),
                                                                                                                                           ('维护通知：2018-07-01 若依系统凌晨维护','1',0xE7BBB4E68AA4E58685E5AEB9,'0','admin','2022-12-11 16:51:52','',NULL,'管理员');
INSERT INTO ruoyi_olive.sys_oper_log (title,business_type,`method`,request_method,operator_type,oper_name,dept_name,oper_url,oper_ip,oper_location,oper_param,json_result,status,error_msg,oper_time,cost_time) VALUES
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,450),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,400),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,34),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,393),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,358),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,336),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,344),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,397),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,360),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,400);
INSERT INTO ruoyi_olive.sys_oper_log (title,business_type,`method`,request_method,operator_type,oper_name,dept_name,oper_url,oper_ip,oper_location,oper_param,json_result,status,error_msg,oper_time,cost_time) VALUES
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,372),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,40),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',1,'java.io.FileNotFoundException: user.xlsx (另一个程序正在使用此文件，进程无法访问。)',NULL,307),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','{"pageSize":"10","pageNum":"1"}','',0,'',NULL,526),
                                                                                                                                                                                                                    ('登录日志',5,'com.olive.web.controller.monitor.SysLoginLogController.export()','POST',1,'admin','','/monitor/logininfor/export','127.0.0.1','内网IP','','',0,'',NULL,27);
INSERT INTO ruoyi_olive.sys_post (post_code,post_name,post_sort,status,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                               ('ceo','董事长',1,'0','admin','2022-12-11 16:51:52','',NULL,''),
                                                                                                                               ('se','项目经理',2,'0','admin','2022-12-11 16:51:52','',NULL,''),
                                                                                                                               ('hr','人力资源',3,'0','admin','2022-12-11 16:51:52','',NULL,''),
                                                                                                                               ('user','普通员工',4,'0','admin','2022-12-11 16:51:52','',NULL,'来一个操作111');
INSERT INTO ruoyi_olive.sys_role (role_name,role_key,role_sort,data_scope,menu_check_strictly,dept_check_strictly,status,del_flag,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                          ('超级管理员','admin',1,'1',1,1,'0','0','admin','2022-12-11 16:51:52','',NULL,'超级管理员'),
                                                                                                                                                                                          ('普通角色','common',2,'1',1,1,'0','0','admin','2022-12-11 16:51:52','admin','2023-03-18 18:49:28','普通角色'),
                                                                                                                                                                                          ('测试','test',0,'1',1,1,'0','0',NULL,'2024-12-23 11:45:20',NULL,NULL,'222');
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,1),
                                                            (2,2),
                                                            (2,3),
                                                            (2,4),
                                                            (2,100),
                                                            (2,101),
                                                            (2,102),
                                                            (2,103),
                                                            (2,104),
                                                            (2,105);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,106),
                                                            (2,107),
                                                            (2,108),
                                                            (2,109),
                                                            (2,110),
                                                            (2,111),
                                                            (2,112),
                                                            (2,113),
                                                            (2,114),
                                                            (2,115);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,116),
                                                            (2,117),
                                                            (2,500),
                                                            (2,501),
                                                            (2,1000),
                                                            (2,1001),
                                                            (2,1002),
                                                            (2,1003),
                                                            (2,1004),
                                                            (2,1005);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,1006),
                                                            (2,1007),
                                                            (2,1008),
                                                            (2,1009),
                                                            (2,1010),
                                                            (2,1011),
                                                            (2,1012),
                                                            (2,1013),
                                                            (2,1014),
                                                            (2,1015);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,1016),
                                                            (2,1017),
                                                            (2,1018),
                                                            (2,1019),
                                                            (2,1020),
                                                            (2,1021),
                                                            (2,1022),
                                                            (2,1023),
                                                            (2,1024),
                                                            (2,1025);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,1026),
                                                            (2,1027),
                                                            (2,1028),
                                                            (2,1029),
                                                            (2,1030),
                                                            (2,1031),
                                                            (2,1032),
                                                            (2,1033),
                                                            (2,1034),
                                                            (2,1035);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,1036),
                                                            (2,1037),
                                                            (2,1038),
                                                            (2,1039),
                                                            (2,1040),
                                                            (2,1041),
                                                            (2,1042),
                                                            (2,1043),
                                                            (2,1044),
                                                            (2,1045);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,1046),
                                                            (2,1047),
                                                            (2,1048),
                                                            (2,1049),
                                                            (2,1050),
                                                            (2,1051),
                                                            (2,1052),
                                                            (2,1053),
                                                            (2,1054),
                                                            (2,1055);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,1056),
                                                            (2,1057),
                                                            (2,1058),
                                                            (2,1059),
                                                            (2,1060),
                                                            (2,2020),
                                                            (2,2022),
                                                            (2,2023),
                                                            (2,2024),
                                                            (2,2025);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,2026),
                                                            (2,2027),
                                                            (2,2028),
                                                            (2,2029),
                                                            (2,2030),
                                                            (2,2031),
                                                            (2,2032),
                                                            (2,2033),
                                                            (2,2034),
                                                            (2,2035);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,2036),
                                                            (2,2037),
                                                            (2,2038),
                                                            (2,2039),
                                                            (2,2040),
                                                            (2,2041),
                                                            (2,2042),
                                                            (2,2043),
                                                            (2,2044),
                                                            (2,2045);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,2046),
                                                            (2,2047),
                                                            (2,2048),
                                                            (2,2049),
                                                            (2,2050),
                                                            (2,2051),
                                                            (2,2052),
                                                            (2,2053),
                                                            (2,2054),
                                                            (2,2055);
INSERT INTO ruoyi_olive.sys_role_menu (role_id,menu_id) VALUES
                                                            (2,2056),
                                                            (2,2057),
                                                            (2,2058),
                                                            (2,2059);
INSERT INTO ruoyi_olive.sys_user (dept_id,user_name,nick_name,user_type,email,phonenumber,sex,avatar,password,status,del_flag,login_ip,login_date,create_by,create_time,update_by,update_time,remark) VALUES
                                                                                                                                                                                                          (103,'admin','若依','00','ry@163.com','15888888888','0','','{bcrypt}$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2','0','0','127.0.0.1','2025-01-04 15:29:14','admin','2022-12-11 16:51:52','admin','2025-01-02 17:55:19','管理员'),
                                                                                                                                                                                                          (105,'ry','李四','00','ry@qq.com','15666666666','1','','{bcrypt}$2a$10$jaxSf9T9pO7QmItYXcfS9uKHDvfeRxVLwyJ0EaF.T.E6jzCJQE1la','0','0','127.0.0.1','2024-01-02 08:56:34','admin','2022-12-11 16:51:52','admin','2024-01-02 08:56:33','测试员'),
                                                                                                                                                                                                          (104,'王五','tony','00','','','0','','{bcrypt}$2a$10$imlt3C0W8Q1NcGqAOlfdSecqHGJjRI7vhGAvOQm/EM6A.07WIAnnu','0','2','',NULL,'admin','2023-03-01 15:54:00','',NULL,NULL),
                                                                                                                                                                                                          (104,'tony','王五','00','','','0','','{bcrypt}$2a$10$MaZb9xI0vZEbN2ossOpMw.CBn2/V4O6hIzTM4HTb12xnlJFQiMe/C','0','0','127.0.0.1','2024-12-22 15:36:24','admin','2023-03-01 15:54:36','admin','2024-12-31 07:59:04',NULL),
                                                                                                                                                                                                          (100,'test03','李柳','00','','','0','','{bcrypt}$2a$10$UR/wNdSYg1dGuZU1YBqoPegjFkQERLwgnL3EGM0sLUx3SIt0fmbCm','0','0','',NULL,'admin','2023-12-29 09:09:07','admin','2024-12-31 09:03:10',NULL),
                                                                                                                                                                                                          (100,'test04','刘溪','00','','','0','','{bcrypt}$2a$10$vHVXHt0LaA4R4ylBbGVPNOrZbwj5n5L8t8I.ZspXNWrU35eY7MgAK','0','0','',NULL,'admin','2023-12-29 09:09:28','',NULL,NULL);
INSERT INTO ruoyi_olive.sys_user_post (user_id,post_id) VALUES
                                                            (1,1),
                                                            (2,2),
                                                            (4,3);
INSERT INTO ruoyi_olive.sys_user_role (user_id,role_id) VALUES
                                                            (1,1),
                                                            (2,2),
                                                            (4,2),
                                                            (4,4),
                                                            (5,2);
